project:
  type: book
  output-dir: docs
  pre-render: R/getGeoPressureTemplateQmd.R

book:
  title: "A User Manual for GeoPressureR"
  author: "Raphaël & Améline Nussbaumer"
  # subtitle
  description: "Learn how to use GeoPressureR with a Swainson's Warbler and a Great Reed Warbler."
  # references: CITATION.cff
  # output-file
  cover-image: "assets/cover.png"
  sharing: [twitter, facebook]
  # downloads: [pdf, epub]
  doi: "10.5281/zenodo.10799355"
  favicon: /assets/favicon.svg
  site-url: https://raphaelnussbaumer.com/GeoPressureManual/
  repo-url: https://github.com/Rafnuss/GeoPressureManual
  issue-url: https://github.com/Rafnuss/GeoPressureManual/issues
  google-analytics: "G-NJ17NCTPB5"
  cookie-consent: true
  search: true
  # navbar:
  sidebar:
    footer: "<a href='https://github.com/Rafnuss/GeoPressureTemplate' target='_blank' class='btn btn-sm btn-outline-primary' role='button'>Start your own study</a>"
  # body-header: ""
  # body-footer
  # page-footer
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  image: "assets/cover.png"
  open-graph: true
  twitter-card: true
  chapters:
    - index.qmd

    - part: "Basic tutorial"
      chapters:
        - tag-object.qmd
        - pressure-map.qmd
        - trajectory.qmd

    - part: "Advanced tutorial"
      chapters:
        - light-map.qmd
        - trajectory-with-wind.qmd

    - part: "Labelling tools"
      chapters:
        - pressurepath.qmd
        - geopressureviz.qmd
        - labelling-tracks.qmd

    - part: "GeoPressureTemplate"
      chapters:
        - geopressuretemplate-intro.qmd
        - geopressuretemplate-label.qmd
        - geopressuretemplate-twilight.qmd
        - geopressuretemplate-wind.qmd
        - geopressuretemplate-workflow.qmd

    - part: "GeoLocator DP"
      chapters:
        - geolocator-intro.qmd
        - geolocator-create.qmd
        - geolocator-read.qmd

  appendices:
    - resources.qmd
    #- visuals.qmd
    - probability-aggregation.qmd

toc: true
number-sections: true

format:
  html:
    theme:
      - cosmo
      - style.scss
    code-link: true
    asciidoc: default

editor: source

bibliography: book.bib
link-citations: true
